### ISSUE TITLE
Front End

### ISSUE THREAD

**Issue by ahmadfarid-059** [GSG-G10/sabbah-reddit#12]
## Tasks

- [x] code index.html
- [x] style index page
- [x] create login form
- [x] create sign up form
- [x] style form pages
- [x] errors pages and style
- [x] profile page and style
- [ ] dom function to create post 
- [ ] fetch endpoints from DOM
- [ ] Dom functions for reacting with posts
