### ISSUE TITLE
create and delete comments

### ISSUE THREAD

**Issue by ahmadfarid-059** [GSG-G10/sabbah-reddit#20]
## Tasks 

- [x] create comment controller
- [x] delete comment controller
- [x] delete comment query
#### Edits

- file structure
- fix eslint issues
