### ISSUE TITLE
like & unlike

### ISSUE THREAD

**Issue by ahmadfarid-059** [GSG-G10/sabbah-reddit#22]
### Tasks

- [x] create delete post controller
- [x] create like query
- [x] create like controller 
- [x] create dislike query
- [x] create dislike controller
- [x] add controllers to the routes
